spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000

logging:
  level:
    org.springframework.security: DEBUG