spring:
  application:
    name: email-service
  kafka:
    consumer:
      bootstrap-servers: broker:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: "com.github.diogodelima.emailservice.dto.UserForgotPasswordDto"
      group-id: email-service
  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false